apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  ingressClassName: public
  tls:
  - hosts:
    - gpmaga.com
    - api.stakswipe.com
    - api.celniker.com
    secretName: quickstart-example-tls
  rules:
  - host: gpmaga.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeserver
            port:
              number: 80
  - host: api.stakswipe.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeserver
            port:
              number: 80
  - host: api.celniker.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cel-vault
            port:
              number: 80