{{- if .Values.createPostgres -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  clusterIP: None
  ports:
  - port: 5432
  selector:
    app: postgres
{{- end -}}