apiVersion: batch/v1
kind: CronJob
metadata:
  name: turn-off-lights
spec:
  schedule: "30 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: turn-off-lights
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["python3",  "/app/scripts/turn_off_lights.py"]
          restartPolicy: Never