apiVersion: batch/v1
kind: CronJob
metadata:
  name: turn-on-lights
spec:
  schedule: "00 17 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: turn-on-lights
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["python3",  "/app/scripts/turn_on_string_lights.py"]
          restartPolicy: Never